# Generated by Django 3.2.3 on 2021-06-07 16:51

from django.db import migrations, models
import myJourneys.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.IntegerField(primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=15, max_digits=15)),
                ('longitude', models.DecimalField(decimal_places=15, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=30)),
                ('email_address', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('language', models.CharField(max_length=30)),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[(myJourneys.models.CarChoice['TUK'], 'TUK-TUK'), (myJourneys.models.CarChoice['MINI'], 'MINI-VAN'), (myJourneys.models.CarChoice['SUV'], 'SPORT-UTILITY VEHICLE'), (myJourneys.models.CarChoice['CONV'], 'CONVERTIBLE'), (myJourneys.models.CarChoice['COUP'], 'COUPE'), (myJourneys.models.CarChoice['LUX_SUV'], 'LUXURY SPORT-UTILITY VEHICLE'), (myJourneys.models.CarChoice['LUX_CONV'], 'LUXURY CONVERTIBLE'), (myJourneys.models.CarChoice['LUX_COUP'], 'LUXURY COUPE')], max_length=10)),
                ('capacity', models.IntegerField(default=0)),
                ('license_plate_number', models.CharField(max_length=11)),
            ],
        ),
    ]
