# Generated by Django 3.2.3 on 2021-06-10 14:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import myJourneys.models


class Migration(migrations.Migration):

    dependencies = [
        ('myJourneys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myJourneys.user')),
            ],
            bases=('myJourneys.user',),
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myJourneys.user')),
                ('vehicle', models.CharField(max_length=100, verbose_name=myJourneys.models.Vehicle)),
            ],
            bases=('myJourneys.user',),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='license_plate_number',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=6)),
                ('notes', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=30)),
                ('assigned_driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myJourneys.driver')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myJourneys.customer')),
                ('drop_off_loc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='do_loc', to='myJourneys.location')),
                ('pick_up_loc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pu_loc', to='myJourneys.location')),
            ],
        ),
    ]
