# Generated by Django 3.2.3 on 2021-06-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myJourneys', '0005_alter_driver_vehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='drop_off_loc',
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='pick_up_loc',
        ),
        migrations.AddField(
            model_name='bookings',
            name='drop_off',
            field=models.CharField(default='drop_off', max_length=100),
        ),
        migrations.AddField(
            model_name='bookings',
            name='pick_up',
            field=models.CharField(default='pick_up', max_length=100),
        ),
    ]
