# Generated by Django 3.2.3 on 2021-06-15 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myJourneys', '0006_auto_20210615_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='assigned_driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myJourneys.driver'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0.75, max_digits=6),
        ),
    ]
